"""Small local operator workspace served by the daemon."""

CONTROL_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>connectd control</title><style>
:root{font-family:system-ui,sans-serif;color:#17211e;background:#f4f7f4}
body{max-width:1100px;margin:auto;padding:24px}h1{margin:0 0 4px;font-size:2rem}h2{margin-top:0}
.sub{color:#53645c;margin-bottom:24px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}
.card{background:white;border:1px solid #d6e0d8;border-radius:14px;padding:20px;margin-bottom:20px;box-shadow:0 3px 12px #183b2510}
label{display:block;font-size:.82rem;font-weight:650;margin:12px 0 4px}input,select,textarea,button{font:inherit}
input,select,textarea{box-sizing:border-box;width:100%;padding:10px;border:1px solid #bbc9bf;border-radius:8px;background:white}input[type=checkbox]{width:auto}
button{border:0;border-radius:8px;background:#196d42;color:white;padding:10px 16px;cursor:pointer;margin-top:12px}
button.secondary{background:#e4eee6;color:#174b30;margin:4px}.row{display:flex;gap:8px;align-items:end}
.row>*{flex:1}.item{border-top:1px solid #e5ebe6;padding:10px 0}.item button{margin:0}
.muted{color:#637269;font-size:.85rem}.error{color:#a12626}.ok{color:#176b3e}
pre{white-space:pre-wrap;word-break:break-word;font-size:.82rem;background:#f5f8f6;padding:12px;border-radius:8px;max-height:300px;overflow:auto}
@media(max-width:720px){.grid{grid-template-columns:1fr}.row{display:block}}
</style></head><body>
<h1>connectd control</h1><div class="sub">Tasks, trusted memory, and verified execution history</div>
<section class="card"><div class="row"><div><label for="token">Operator token</label><input id="token" type="password" autocomplete="off" placeholder="Paste your operator bearer token"></div><div><button id="load">Load workspace</button></div></div><p class="muted">The token stays in this browser tab's memory and is not saved.</p><div id="status"></div></section>
<section class="card" id="onboarding" hidden><h2>Organization setup</h2>
<div class="grid"><form id="new-org"><h3>Create organization</h3>
<label for="org-name">Organization name</label><input id="org-name" required maxlength="200">
<button type="submit">Create organization</button></form>
<form id="new-user"><h3>Add a user</h3>
<label for="user-org">Organization</label><select id="user-org"></select>
<label for="user-name">Display name</label><input id="user-name" required maxlength="200">
<label for="user-role">Role</label><select id="user-role"><option>viewer</option><option>operator</option><option>admin</option></select>
<button type="submit">Issue user token</button></form></div>
<div id="issued-token" class="muted">New user tokens are shown once.</div><h3>Users</h3><div id="org-users" class="muted">Select an organization.</div>
<h3>Registry shares</h3><div id="org-shares" class="muted">Select an organization.</div>
<form id="new-share"><h4>Share a resource</h4><label for="share-target">Target organization ID</label><input id="share-target" required><label for="share-kind">Resource</label><select id="share-kind"><option value="tool">Tool</option><option value="node">Compute node</option></select><label for="share-resource">Resource ID</label><input id="share-resource" required placeholder="Use * for the entire registry"><button type="submit">Grant share</button></form>
<form id="org-settings"><h3>Provisioning policy</h3><label><input id="allow-unquoted-runpod" type="checkbox"> Allow RunPod creation when the GPU catalog quote is unavailable</label><p class="muted">The created Pod rate is still checked against the operator cap and an over-cap Pod is deleted.</p><button type="submit">Save policy</button></form>
<form id="pod-quote"><h3>Preview RunPod GPU price</h3><label for="pod-gpu-type">GPU type ID</label><input id="pod-gpu-type" required><label for="pod-gpu-count">GPU count</label><input id="pod-gpu-count" type="number" min="1" max="16" value="1" required><label for="pod-cloud">Cloud type</label><select id="pod-cloud"><option value="SECURE">Secure</option><option value="COMMUNITY">Community</option></select><button type="submit">Get catalog price</button><div id="pod-quote-result" class="muted">GPU list price only; storage and final Pod billing are separate.</div></form></section>
<div class="grid"><section class="card" id="new-task-card"><h2>New task</h2><form id="new-task">
<label for="title">Title</label><input id="title" required maxlength="500">
<label for="privacy">Privacy</label><select id="privacy"><option>public</option><option>low_sensitive</option><option>repo_sensitive</option><option>secret_sensitive</option></select>
<label for="scope">Memory scope</label><input id="scope" required placeholder="repo:my-project">
<label for="profile">Execution profile</label><select id="profile"><option>balanced</option><option>dev_fast</option><option>prod_secure</option></select>
<button type="submit">Create task</button></form></section>
<section class="card"><h2>Tasks</h2><div id="tasks" class="muted">Load workspace to see tasks.</div></section></div>
<section class="card"><h2>Task workspace</h2><div id="task-detail" class="muted">Select a task to inspect its steps and budget.</div></section>
<div class="grid"><section class="card"><h2>Audit timeline</h2><div id="audit" class="muted">Select a task.</div></section>
<section class="card" id="candidates-card"><h2>Memory candidates</h2><div id="candidates" class="muted">Load workspace to review candidates.</div></section></div>
<section class="card" id="memory-card"><h2>Memory ledger</h2><div class="row"><div><label for="memory-scope">Scope</label><input id="memory-scope" placeholder="repo:my-project"></div><div><button id="load-memory">Inspect claims</button></div></div><div id="memory-ledger" class="muted">Enter a scope to inspect promoted, stale, superseded, and pending claims.</div></section>
<section class="card" id="nodes-card"><h2>Compute nodes</h2><div id="compute-nodes" class="muted">Load workspace to inspect node health and capacity.</div></section>
<section class="card" id="bindings-card"><h2>Legacy tool bindings</h2><div id="binding-proposals" class="muted">Load workspace to review imported tools.</div></section>
<script>
let token='',identity=null;const byId=id=>document.getElementById(id);
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw Error((await r.text()).slice(0,300));return r.json()}
function status(message,error=false){byId('status').textContent=message;byId('status').className=error?'error':'ok'}
function element(tag,text){const node=document.createElement(tag);node.textContent=text;return node}
async function load(){token=byId('token').value.trim();if(!token){status('Enter an operator token.',true);return}try{identity=await api('/api/v1/me');renderTasks(await api('/api/v1/tasks'));byId('new-task-card').hidden=identity.role==='viewer';const global=identity.bootstrap;byId('candidates-card').hidden=!global;byId('memory-card').hidden=!global;byId('nodes-card').hidden=!global;byId('bindings-card').hidden=identity.role!=='admin';byId('onboarding').hidden=identity.role!=='admin';byId('new-org').hidden=!global;byId('org-settings').hidden=global;byId('new-share').hidden=global;if(global){const [candidates,nodes,orgs,bindings]=await Promise.all([api('/api/v1/memory/candidates'),api('/api/v1/compute/nodes'),api('/api/v1/orgs'),api('/api/v1/tools/binding-proposals')]);renderCandidates(candidates);renderNodes(nodes);renderOrganizations(orgs);await loadUsers();renderBindings(bindings)}else if(identity.role==='admin'){renderOrganizations([{org_id:identity.org_id,name:'Current organization'}]);await loadUsers();renderBindings(await api('/api/v1/tools/binding-proposals'))}status('Workspace loaded for '+identity.role+'.')}catch(e){status(e.message,true)}}
function renderOrganizations(orgs){const select=byId('user-org');select.replaceChildren();for(const org of orgs){const option=element('option',org.name+' · '+org.org_id);option.value=org.org_id;select.append(option)}}
async function loadUsers(){const org=byId('user-org').value;if(!org)return;const users=await api('/api/v1/orgs/'+encodeURIComponent(org)+'/users');await loadShares(org);const root=byId('org-users');root.replaceChildren();const settings=await api('/api/v1/orgs/'+encodeURIComponent(org)+'/settings');byId('allow-unquoted-runpod').checked=settings.allow_unquoted_runpod;if(!users.length){root.textContent='No users yet.';return}for(const user of users){const item=element('div',user.display_name+' | '+user.role+' | '+(user.active?'active':'revoked'));item.className='item';if(user.active&&user.user_id!==identity.user_id){const button=element('button','Revoke');button.className='secondary';button.onclick=async()=>{try{await api('/api/v1/orgs/'+encodeURIComponent(org)+'/users/'+encodeURIComponent(user.user_id),{method:'DELETE'});await loadUsers();status('User revoked.')}catch(error){status(error.message,true)}};item.append(button)}root.append(item)}}
async function loadShares(org){const shares=await api('/api/v1/orgs/'+encodeURIComponent(org)+'/shares');const root=byId('org-shares');root.replaceChildren();if(!shares.length){root.textContent='No registry resources shared from this organization.';return}for(const share of shares){const scope=share.resource_id==='*'?'entire registry':share.resource_id;const item=element('div',share.resource_kind+' · '+scope+' → '+share.target_org_id);item.className='item';if(!identity.bootstrap){const button=element('button','Revoke');button.className='secondary';button.onclick=async()=>{try{const path='/api/v1/orgs/'+encodeURIComponent(org)+'/shares/'+encodeURIComponent(share.resource_kind)+'/'+encodeURIComponent(share.resource_id)+'/'+encodeURIComponent(share.target_org_id);await api(path,{method:'DELETE'});await loadShares(org);status('Share revoked.')}catch(error){status(error.message,true)}};item.append(button)}root.append(item)}}
byId('user-org').onchange=()=>loadUsers().catch(error=>status(error.message,true));
function renderTasks(tasks){const root=byId('tasks');root.replaceChildren();if(!tasks.length){root.textContent='No tasks yet.';return}for(const task of tasks){const item=element('div',task.title+' · '+task.privacy_class+' · '+task.status);item.className='item';const btn=element('button','Open task');btn.className='secondary';btn.onclick=()=>showTask(task.task_id);item.append(btn);root.append(item)}}
function renderCandidates(items){const root=byId('candidates');root.replaceChildren();if(!items.length){root.textContent='No pending candidates.';return}for(const claim of items){const item=element('div',claim.claim_text);item.className='item';const btn=element('button','Promote');btn.className='secondary';btn.onclick=async()=>{try{await api('/api/v1/memory/claims/'+encodeURIComponent(claim.claim_id)+'/promote',{method:'POST'});load()}catch(e){status(e.message,true)}};item.append(btn);root.append(item)}}
function renderBindings(items){const root=byId('binding-proposals');root.replaceChildren();if(!items.length){root.textContent='No imported tools await binding.';return}for(const item of items){const card=element('div',item.legacy_name+' · '+item.source+' · '+item.review_status);card.className='item';card.append(element('pre',JSON.stringify({suggested_handler_id:item.suggested_handler_id,schema:item.schema,effect_tier:item.effect_tier},null,2)));root.append(card)}}
function renderNodes(nodes){const root=byId('compute-nodes');root.replaceChildren();if(!nodes.length){root.textContent='No compute nodes registered.';return}for(const node of nodes){const item=element('div',node.node_id+' · '+node.model_id+' · '+(node.healthy?'healthy':'unavailable'));item.className='item';const detail=element('pre',JSON.stringify({last_health_at:node.last_health_at,capacity:node.capacity_json?JSON.parse(node.capacity_json):null},null,2));item.append(detail);const button=element('button','Probe now');button.className='secondary';button.onclick=async()=>{try{await api('/api/v1/compute/nodes/'+encodeURIComponent(node.node_id)+'/probe',{method:'POST'});await load()}catch(e){status(e.message,true)}};if(node.last_health_at!==null||node.healthy===false)item.append(button);root.append(item)}}
function renderAudit(audit){const root=byId('audit');root.replaceChildren();const groups=[['Decision',audit.decisions,'created_at'],['Grant',audit.grants,'issued_at'],['Invocation',audit.invocations,'created_at'],['Legacy audit',audit.legacy_tool_audit,'created_at']];const events=groups.flatMap(([label,rows,time])=>rows.map(row=>({label,at:row[time]||'',row}))).sort((a,b)=>a.at.localeCompare(b.at));if(!events.length){root.textContent='No audit events for this task.';return}for(const event of events){const item=element('div',event.label+' · '+event.at);item.className='item';item.append(element('pre',JSON.stringify(event.row,null,2)));root.append(item)}}
async function showTask(id){try{const base='/api/v1/tasks/'+encodeURIComponent(id);const [task,steps,budgets,audit]=await Promise.all([api(base),api(base+'/steps'),api(base+'/budgets'),api(base+'/audit')]);const root=byId('task-detail');root.replaceChildren();root.append(element('h3',task.title),element('p',task.privacy_class+' · '+task.execution_profile+' · '+task.status));const summary=element('div','Steps: '+steps.length+' · Budgets: '+budgets.budgets.length);summary.className='muted';root.append(summary);const budgetList=element('div','');for(const budget of budgets.budgets){const line=element('div',budget.period+' budget: $'+(budget.amount_cents/100).toFixed(2));line.className='item';budgetList.append(line)}if(budgets.records.length){const reserved=budgets.records.reduce((sum,row)=>sum+row.amount_cents,0);budgetList.append(element('p','Ledger entries: '+budgets.records.length+' | total $'+(reserved/100).toFixed(2)))}root.append(budgetList);if(identity.role!=='viewer'&&!task.is_terminal){const form=document.createElement('form');const heading=element('h4','Set spend budget');const period=document.createElement('select');for(const value of ['daily','weekly','monthly']){const option=element('option',value);option.value=value;period.append(option)}const amount=document.createElement('input');amount.type='number';amount.min='0';amount.step='0.01';amount.required=true;amount.placeholder='USD amount';const button=element('button','Save budget');button.type='submit';form.append(heading,period,amount,button);form.onsubmit=async event=>{event.preventDefault();try{await api(base+'/budgets/'+period.value,{method:'PUT',body:JSON.stringify({amount_usd:amount.value})});await showTask(id);status('Budget saved.')}catch(error){status(error.message,true)}};root.append(form)}for(const step of steps){const item=element('div','#'+step.step_number+' · '+step.status+' · '+step.instruction);item.className='item';if(step.result_summary)item.append(element('p',step.result_summary));root.append(item)}if(identity.role!=='viewer'&&!task.is_terminal){const form=document.createElement('form');const label=element('label','New step instruction');const input=document.createElement('textarea');input.required=true;input.rows=3;const button=element('button','Add step');button.type='submit';form.append(label,input,button);form.onsubmit=async event=>{event.preventDefault();try{await api(base+'/steps',{method:'POST',body:JSON.stringify({instruction:input.value.trim()})});await showTask(id);renderTasks(await api('/api/v1/tasks'));status('Step added.')}catch(error){status(error.message,true)}};root.append(form)}renderAudit(audit)}catch(e){status(e.message,true)}}
byId('load-memory').onclick=async()=>{const scope=byId('memory-scope').value.trim();if(!scope){status('Enter a memory scope.',true);return}try{const result=await api('/api/v1/memory/recall',{method:'POST',body:JSON.stringify({scope,max_items:100})});byId('memory-ledger').replaceChildren(element('pre',JSON.stringify(result.items,null,2)))}catch(e){status(e.message,true)}};
byId('load').onclick=load;
byId('new-org').onsubmit=async e=>{e.preventDefault();try{const org=await api('/api/v1/orgs',{method:'POST',body:JSON.stringify({name:byId('org-name').value.trim()})});byId('org-name').value='';status('Created organization '+org.name);await load();byId('user-org').value=org.org_id;await loadUsers()}catch(error){status(error.message,true)}};
byId('org-settings').onsubmit=async e=>{e.preventDefault();const org=byId('user-org').value;try{await api('/api/v1/orgs/'+encodeURIComponent(org)+'/settings',{method:'PUT',body:JSON.stringify({allow_unquoted_runpod:byId('allow-unquoted-runpod').checked})});status('Provisioning policy saved.')}catch(error){status(error.message,true)}};
byId('new-share').onsubmit=async e=>{e.preventDefault();const org=byId('user-org').value;try{await api('/api/v1/orgs/'+encodeURIComponent(org)+'/shares',{method:'POST',body:JSON.stringify({target_org_id:byId('share-target').value.trim(),resource_kind:byId('share-kind').value,resource_id:byId('share-resource').value.trim()})});byId('share-target').value='';byId('share-resource').value='';await loadShares(org);status('Registry share granted.')}catch(error){status(error.message,true)}};
byId('pod-quote').onsubmit=async e=>{e.preventDefault();const org=byId('user-org').value;try{const quote=await api('/api/v1/orgs/'+encodeURIComponent(org)+'/provisioning/runpod/quote',{method:'POST',body:JSON.stringify({gpu_type_id:byId('pod-gpu-type').value.trim(),gpu_count:Number(byId('pod-gpu-count').value),cloud_type:byId('pod-cloud').value})});byId('pod-quote-result').textContent='$'+quote.gpu_hourly_usd+'/hour GPU catalog list price · '+quote.availability+' availability. Storage excluded; final Pod rate is verified after creation.'}catch(error){status(error.message,true)}};
byId('new-user').onsubmit=async e=>{e.preventDefault();try{const org=byId('user-org').value;const user=await api('/api/v1/orgs/'+encodeURIComponent(org)+'/users',{method:'POST',body:JSON.stringify({display_name:byId('user-name').value.trim(),role:byId('user-role').value})});byId('issued-token').replaceChildren(element('pre',user.token));byId('user-name').value='';status('Created user '+user.user_id+'. Copy the token now; it will not be shown again.');await loadUsers()}catch(error){status(error.message,true)}};
byId('new-task').onsubmit=async e=>{e.preventDefault();try{const result=await api('/api/v1/tasks',{method:'POST',body:JSON.stringify({title:byId('title').value,privacy_class:byId('privacy').value,memory_scope:byId('scope').value,execution_profile:byId('profile').value})});status('Created task '+result.task_id);byId('title').value='';await load()}catch(error){status(error.message,true)}};
</script></body></html>"""
