"""Unified relational schema and SQLAlchemy engine configuration."""

from sqlalchemy import Boolean, CheckConstraint, Column, Float, ForeignKey, Index, Integer, MetaData, PrimaryKeyConstraint, String, Table, Text, create_engine, event
from sqlalchemy.engine import Engine


metadata = MetaData()

organizations = Table("organizations", metadata,
    Column("org_id", String, primary_key=True),
    Column("name", String, nullable=False),
    Column("created_at", String, nullable=False),
    Column("allow_unquoted_runpod", Boolean, nullable=False, server_default="0"),
    Column("memory_authority", String, nullable=False, server_default="hybrid"),
    CheckConstraint("memory_authority IN ('session_auto','hybrid','human_gated')"),
)
operator_users = Table("operator_users", metadata,
    Column("user_id", String, primary_key=True),
    Column("org_id", String, ForeignKey("organizations.org_id"), nullable=False),
    Column("display_name", String, nullable=False),
    Column("role", String, nullable=False),
    Column("token_hash", String, nullable=False, unique=True),
    Column("active", Boolean, nullable=False, server_default="1"),
    Column("created_at", String, nullable=False),
    CheckConstraint("role IN ('admin','operator','viewer')"),
)

tasks = Table("tasks", metadata,
    Column("task_id", String, primary_key=True),
    Column("org_id", String, ForeignKey("organizations.org_id"), nullable=False, server_default="default"),
    Column("title", Text, nullable=False),
    Column("goal", Text, nullable=False, server_default=""),
    Column("priority", String, nullable=False, server_default="normal"),
    Column("created_by", String, nullable=False, server_default="operator"),
    Column("metadata_json", Text, nullable=False, server_default="{}"),
    Column("privacy_class", String, nullable=False),
    Column("memory_scope", String, nullable=False),
    Column("execution_profile", String, nullable=False, server_default="balanced"),
    Column("status", String, nullable=False, server_default="active"),
    Column("is_terminal", Boolean, nullable=False, server_default="0"),
    Column("origin", String, nullable=False, server_default="connectd"),
    Column("created_at", String, nullable=False),
    Column("updated_at", String),
    CheckConstraint("privacy_class IN ('public','low_sensitive','repo_sensitive','secret_sensitive')"),
    CheckConstraint("status IN ('active','pending_clarification','completed','failed','legacy_audit_stub')"),
)
task_steps = Table("task_steps", metadata,
    Column("step_id", String, primary_key=True),
    Column("task_id", String, ForeignKey("tasks.task_id", ondelete="CASCADE"), nullable=False),
    Column("step_number", Integer, nullable=False),
    Column("instruction", Text, nullable=False),
    Column("status", String, nullable=False, server_default="pending"),
    Column("assigned_worker_id", String),
    Column("lease_token", String),
    Column("lease_expires_at", String),
    Column("result_summary", Text),
    CheckConstraint("status IN ('pending','claimed','done','failed')"),
)
Index("uq_task_step_number", task_steps.c.task_id, task_steps.c.step_number, unique=True)
Index("idx_task_steps_claim", task_steps.c.status, task_steps.c.lease_expires_at)
artifacts = Table("artifacts", metadata,
    Column("artifact_id", String, primary_key=True),
    Column("task_id", String, ForeignKey("tasks.task_id", ondelete="CASCADE"), nullable=False),
    Column("kind", String, nullable=False),
    Column("storage_path", Text, nullable=False),
    Column("content_hash", String),
    Column("created_at", String, nullable=False),
)
tool_registry = Table("tool_registry", metadata,
    Column("tool_id", String, primary_key=True),
    Column("owner_org_id", String, ForeignKey("organizations.org_id"), nullable=False,
           server_default="default"),
    Column("name", String, nullable=False),
    Column("domain_path", String, nullable=False),
    Column("schema_json", Text, nullable=False),
    Column("effect_tier", Integer, nullable=False),
    Column("active", Boolean, nullable=False, server_default="1"),
    Column("status", String, nullable=False, server_default="active"),
    Column("origin", String, nullable=False, server_default="connectd"),
    Column("provider_tier", String),
    Column("effect_class", String),
    Column("is_financial", Boolean, nullable=False, server_default="0"),
    Column("cost_per_invocation_cents", Integer, nullable=False, server_default="0"),
    Column("pricing_model", String),
    CheckConstraint("effect_tier BETWEEN 0 AND 2"),
    CheckConstraint("cost_per_invocation_cents >= 0"),
)
governance_decisions = Table("governance_decisions", metadata,
    Column("decision_id", String, primary_key=True),
    Column("task_id", String, ForeignKey("tasks.task_id"), nullable=False),
    Column("principal_id", String, nullable=False),
    Column("tool_id", String, ForeignKey("tool_registry.tool_id"), nullable=False),
    Column("result", String, nullable=False),
    Column("reason", String, nullable=False),
    Column("created_at", String, nullable=False),
    CheckConstraint("result IN ('permit','deny')"),
)
governance_grants = Table("governance_grants", metadata,
    Column("grant_id", String, primary_key=True),
    Column("decision_id", String, ForeignKey("governance_decisions.decision_id"), nullable=False),
    Column("task_id", String, ForeignKey("tasks.task_id"), nullable=False),
    Column("principal_id", String, nullable=False),
    Column("tool_id", String, ForeignKey("tool_registry.tool_id"), nullable=False),
    Column("frozen_args_hash", String, nullable=False),
    Column("signature", Text, nullable=False),
    Column("status", String, nullable=False, server_default="issued"),
    Column("issued_at", String, nullable=False),
    Column("expires_at", String, nullable=False),
    CheckConstraint("status IN ('issued','redeemed','revoked','legacy_expired')"),
)
governance_approvals = Table("governance_approvals", metadata,
    Column("approval_id", String, primary_key=True),
    Column("task_id", String, ForeignKey("tasks.task_id"), nullable=False),
    Column("principal_id", String, nullable=False),
    Column("tool_id", String, ForeignKey("tool_registry.tool_id"), nullable=False),
    Column("frozen_args_hash", String, nullable=False),
    Column("expires_at", String, nullable=False),
    Column("consumed", Boolean, nullable=False, server_default="0"),
    Column("approved_by", String, nullable=False),
)
quota_budgets = Table("quota_budgets", metadata,
    Column("budget_id", String, primary_key=True),
    Column("task_id", String, ForeignKey("tasks.task_id"), nullable=False),
    Column("period", String, nullable=False),
    Column("amount_cents", Integer, nullable=False),
    Column("approved_by", String, nullable=False),
    Column("created_at", String, nullable=False),
    CheckConstraint("period IN ('daily','weekly','monthly')"),
    CheckConstraint("amount_cents >= 0"),
)
Index("uq_quota_budget_period", quota_budgets.c.task_id, quota_budgets.c.period, unique=True)
quota_records = Table("quota_records", metadata,
    Column("record_id", String, primary_key=True),
    Column("task_id", String, ForeignKey("tasks.task_id"), nullable=False),
    Column("tool_id", String, ForeignKey("tool_registry.tool_id")),
    Column("grant_id", String, ForeignKey("governance_grants.grant_id")),
    Column("node_id", String, ForeignKey("compute_nodes.node_id")),
    Column("source_type", String, nullable=False),
    Column("amount_cents", Integer, nullable=False),
    Column("reserved_cents", Integer, nullable=False),
    Column("actual_units", Integer),
    Column("status", String, nullable=False, server_default="reserved"),
    Column("created_at", String, nullable=False),
    CheckConstraint("amount_cents >= 0"),
    CheckConstraint("status IN ('reserved','settled')"),
)
tool_invocation_logs = Table("tool_invocation_logs", metadata,
    Column("invocation_id", String, primary_key=True),
    Column("grant_id", String, ForeignKey("governance_grants.grant_id")),
    Column("task_id", String, ForeignKey("tasks.task_id"), nullable=False),
    Column("tool_id", String, ForeignKey("tool_registry.tool_id"), nullable=False),
    Column("outcome", String, nullable=False),
    Column("created_at", String, nullable=False),
)
legacy_tool_audit = Table("legacy_tool_audit", metadata,
    Column("seq", Integer, primary_key=True),
    Column("kind", String, nullable=False),
    Column("body_json", Text),
    Column("body_hash", String, nullable=False),
    Column("created_at", String, nullable=False),
    Column("prev_hash", String, nullable=False),
    Column("record_hash", String, nullable=False),
    Column("task_id", String, ForeignKey("tasks.task_id")),
    Column("grant_id", String, ForeignKey("governance_grants.grant_id")),
)
memory_claims = Table("memory_claims", metadata,
    Column("claim_id", String, primary_key=True),
    Column("org_id", String, ForeignKey("organizations.org_id"), nullable=False,
           server_default="default"),
    Column("task_id", String, ForeignKey("tasks.task_id")),
    Column("scope", String, nullable=False),
    Column("claim_text", Text, nullable=False),
    Column("status", String, nullable=False, server_default="pending"),
    Column("is_trusted", Boolean, nullable=False, server_default="0"),
    Column("origin", String, nullable=False),
    Column("promoted_by", String),
    Column("created_at", String, nullable=False),
    Column("confidence", Float),
    Column("confidence_label", String),
    Column("valid_from", String),
    Column("valid_until", String),
    Column("learned_at", String),
    Column("last_verified_at", String),
    Column("tags_json", Text, nullable=False, server_default="[]"),
    Column("superseded_by", String),
    CheckConstraint("status IN ('pending','promoted','rejected')"),
)
Index("idx_memory_recall", memory_claims.c.scope, memory_claims.c.is_trusted)
Index("idx_memory_task", memory_claims.c.org_id, memory_claims.c.task_id, memory_claims.c.status)
claim_provenance = Table("claim_provenance", metadata,
    Column("provenance_id", String, primary_key=True),
    Column("claim_id", String, ForeignKey("memory_claims.claim_id", ondelete="CASCADE"), nullable=False),
    Column("source_uri", Text, nullable=False),
    Column("source_hash", String, nullable=False),
    Column("created_at", String, nullable=False),
    Column("source_id", String),
    Column("origin", String),
    Column("title", Text),
    Column("location", Text),
    Column("mime_type", String),
)
claim_contradictions = Table("claim_contradictions", metadata,
    Column("contradiction_id", String, primary_key=True),
    Column("existing_claim_id", String, ForeignKey("memory_claims.claim_id"), nullable=False),
    Column("new_claim_id", String, ForeignKey("memory_claims.claim_id"), nullable=False),
    Column("status", String, nullable=False, server_default="open"),
    Column("resolution_notes", Text),
)
compute_nodes = Table("compute_nodes", metadata,
    Column("node_id", String, primary_key=True),
    Column("owner_org_id", String, ForeignKey("organizations.org_id"), nullable=False,
           server_default="default"),
    Column("provider_type", String, nullable=False),
    Column("privacy_tier", String, nullable=False),
    Column("healthy", Boolean, nullable=False, server_default="1"),
    Column("airgapped", Boolean, nullable=False, server_default="0"),
    Column("billing_mode", String, nullable=False, server_default="free"),
    Column("endpoint_url", Text),
    Column("model_id", String),
    Column("max_context", Integer),
    Column("allowed_privacy_json", Text),
    Column("ca_cert_path", Text),
    Column("client_cert_path", Text),
    Column("client_key_path", Text),
    Column("pricing_model", Text),
    Column("tokenizer_json", Text),
    Column("preflight_url", Text),
    Column("health_url", Text),
    Column("manager_id", String),
    Column("last_health_at", String),
    Column("capacity_json", Text),
    CheckConstraint("privacy_tier IN ('local_only','private_rented','external')"),
)
registry_shares = Table("registry_shares", metadata,
    Column("owner_org_id", String, ForeignKey("organizations.org_id"), nullable=False),
    Column("target_org_id", String, ForeignKey("organizations.org_id"), nullable=False),
    Column("resource_kind", String, nullable=False),
    Column("resource_id", String, nullable=False),
    Column("created_by", String, nullable=False),
    Column("created_at", String, nullable=False),
    PrimaryKeyConstraint("owner_org_id", "target_org_id", "resource_kind", "resource_id"),
    CheckConstraint("resource_kind IN ('tool','node')"),
)
Index("idx_registry_shares_target", registry_shares.c.target_org_id,
      registry_shares.c.resource_kind, registry_shares.c.resource_id)

workload_placements = Table("workload_placements", metadata,
    Column("placement_id", String, primary_key=True),
    Column("task_id", String, ForeignKey("tasks.task_id", ondelete="CASCADE"), nullable=False),
    Column("node_id", String, ForeignKey("compute_nodes.node_id"), nullable=False),
    Column("model_id", String, nullable=False),
    Column("status", String, nullable=False, server_default="reserved"),
    Column("created_at", String, nullable=False),
)
routing_decisions = Table("routing_decisions", metadata,
    Column("routing_id", String, primary_key=True),
    Column("task_id", String, ForeignKey("tasks.task_id"), nullable=False),
    Column("provider", String, nullable=False),
    Column("resolved_tool_id", String),
    Column("status", String, nullable=False),
    Column("reason", String),
    Column("hops_json", Text, nullable=False),
    Column("confidences_json", Text, nullable=False),
    Column("latency_ms", Integer, nullable=False),
    Column("created_at", String, nullable=False),
)
worker_sessions = Table("worker_sessions", metadata,
    Column("token_hash", String, primary_key=True),
    Column("task_id", String, ForeignKey("tasks.task_id", ondelete="CASCADE"), nullable=False),
    Column("worker_id", String, nullable=False),
    Column("expires_at", String, nullable=False),
    Column("revoked", Boolean, nullable=False, server_default="0"),
)
legacy_records = Table("legacy_records", metadata,
    Column("source", String, primary_key=True),
    Column("table_name", String, primary_key=True),
    Column("record_key", String, primary_key=True),
    Column("payload_json", Text),
    Column("payload_hash", String, nullable=False),
    Column("imported_at", String, nullable=False),
)


def engine_for(url: str) -> Engine:
    engine = create_engine(url, future=True)
    if engine.dialect.name == "sqlite":
        @event.listens_for(engine, "connect")
        def enable_foreign_keys(dbapi_connection, _connection_record):
            cursor = dbapi_connection.cursor()
            cursor.execute("PRAGMA foreign_keys=ON")
            cursor.close()
    return engine
